name: Node.js CI + Continuous Delivery

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Frontend build
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build --if-present

      # Backend build
      - name: Install backend dependencies
        working-directory: ./backend~
        run: npm install

      - name: Test backend
        working-directory: ./backend
        run: npm test --if-present

      # 🔹 New Step for Continuous Delivery
      - name: Upload build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/


          
